### ISSUE TITLE
feature request: glassbox prescription function

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#1]
highly opinionated rx function to use right out-of-the-box

requirements:

- [x] integrate settings flags for every parameter
- [x] add interactive flag to step-wise through each step for parameter tuning
- [x] ~~add ability to step backwards during interactive mode to `undo` an operation~~

example:
```r
glassbox <- function(eye, detrend = FALSE) {
  eyeris::load() |>
  eyeris::deblink(extend = 75) |>
  eyeris::despeed(n = 8) |>
  eyeris::butterfilt(type = 'low', order = 4, freq = 0.5) |>
}
```

**Comment by shawntz** [comment]
make default value for `deblink` 50ms instead of 75ms

**Comment by shawntz** [comment]
the task: " add ability to step backwards during interactive mode to undo an operation" has been cancelled and instead has been replaced with an abort call

**Comment by mh105** [comment]
Is the abort call still able to step back one operation at a time or is it going to abort the entire pipeline?

**Comment by shawntz** [comment]
@mh105 for now, it's going to abort the entire pipeline for the provided `.asc` file. i'm not sure whether the implementation of a history + undo/redo system on top of the base `eyeris` object will pay off given that most pupil datasets probably won't take too long to run the `glassbox()` pipeline on interactively (though, i'm only testing on smaller test `.asc` files right now...)

do you think it's worth implementing this undo feature for `beta` release, or should i focus on this later for `v1.0.0`?

**Comment by mh105** [comment]
I initially thought the reason that you are updating the array `eyeris$timeseries` and keeping a copy of all the past processing outcomes is because you want to easily go back to a previous step. But now I realize that you probably need all the intermediate time series for generating the plot.

Could you point me to the `abort` implementation and explain what it is supposed to do? Maybe I'm misunderstanding, but my gut feeling is that it might be the cleanest to avoid introducing another call that people need to remember. In my mind a typical workflow would be: `eyeris` simply generates a plot after running an entire pipeline - if people don't like the results, they just start from scratch again and recreate the `eyeris` object themselves. Everyone should know how to do everything again since they have gotten this far. Are there specific considerations that you have in mind for the `abort` call?

**Comment by shawntz** [comment]
sorry i think my use of the term `abort` may have been misleading here. what i meant to convey was the following workflow:
1. user calls the `glassbox()` function
2. user is presented with each step, one at a time, along with a plot of the data from that step (fyi, it currently is just one epoch, but based on your response to #7, will be updated to include 3 random epochs), and then is prompted to indicate `yes` or `no` depending on whether they want to continue on to the next step (prompting only occurs if `interactive` flag == `TRUE`, otherwise, it runs through every step).
3. if user indicates `no` on the prompt dialogue, then `glassbox()` exits and saves out whatever steps were completed up to the `no` (so the user can further work with / evaluate that `eyeris` data object before rerunning `glasbox()` again. 

thus, there is no formal `undo` step at this moment in time as the user is just provided the latest output upon exit for further inspection. 

imo, the key design feature that makes the `undo` feature's utility questionable (outside of speed / efficiency concerns by not having to re-run `ok` steps) is that the parameters that users want to override are passed into `glassbox()` at the time of function call. therefore, if we allowed the user to `undo` a step while iterating through the steps within the `glassbox()` wrapper, then we would now need to provide a supplemental mechanism to inject the updated parameters beyond the initial `glassbox()` call. this isn't necessarily a bad / hard thing to do, but begs the question as to how relevant / useful such an implementation would be. 

@mh105 - given this, assuming we **do want to** add this functionality in, then let me know if you think the following will be a happy intermediate behavior:
- [ ] instead of just `yes` and `no` options for the prompt, we include `yes`, `no`, and `undo`. critically, there will be no formal "redoing" (or forward jumping back to previously run steps), but only backwards subtraction of steps. 
- [ ] thus, the call to `undo` will essentially revert to the `n-1` state of the `eyeris` object; so, for any given `glassbox()` function call, we will essentially always store the `n-1` `eyeris` object along with `n` for each step, meaning we could recursively get back to the starting `load()` step each time, and moving forward would mean literally indicating `yes` to the steps that are now coming up after performing `undo` (but not allowing the user to automatically get back to their previous `n+1` call from whatever state they're in following an `undo`). basically, i want to avoid having to store multiple undo/redo steps in memory, so with the approach i laid out, the problem is simplified because after an `undo` call, then each previously run step is purged from memory.

**Comment by mh105** [comment]
Thanks for your thoughts on this @shawntschwartz. Yes I understand now - I didn't realize that you are referring to an interactive session with `yes/no` prompting. I agree with your comments that 
> imo, the key design feature that makes the undo feature's utility questionable (outside of speed / efficiency concerns by not having to re-run ok steps) is that the parameters that users want to override are passed into glassbox() at the time of function call. therefore, if we allowed the user to undo a step while iterating through the steps within the glassbox() wrapper, then we would now need to provide a supplemental mechanism to inject the updated parameters beyond the initial glassbox() call.

Like you said, it's not technically hard, but I don't like its programmatic implications, because it introduces a problem of "multiple realization" with using the `glassbox()` call. I.e., a user could arrive at the same result either by modifying the initial `glassbox()` call or doing `undo` and then modifying parameters.

For now, let's not even allow the option of `undo` when prompting. Probably for the next release, it will be useful to introduce a proper interactive mode of `glassbox()` where it will start with no parameter input, but instead, the parameters for each step are entered dynamically via prompt with default values already populated -> `glassbox()` runs it, displays a diagnostic plot -> asks via prompt to `yes`, `no`, or `undo`. Then if user chooses to `undo`, they are taken back to the prompt where they are entering the parameters for each step and given the opportunity to modify it in real time and see the results. To me, this is what I expect an interactive session to be able to do.

Because of that, maybe instead of calling the current prompting as `interactive == TRUE`, you could rename it as `confirmation`, which defaults to FALSE. Later when we add the full interactive functionality, you can introduce the `interactive` flag to `glassbox()`.

What do you think?

**Comment by shawntz** [comment]
thanks @mh105 -- i appreciate your added thoughts on this; it sounds like we've converged on what to do both in the near and long term, but for right now, the latter won't dramatically impact the utility of `eyeris` for end users! :100:
