### ISSUE TITLE
feature request: asymmetrical blink padding

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#30]
requirements:

- [ ] allow users to specify both forward and backward `ms` values (instead of the current symmetrical implementation)

**Comment by shawntz** [comment]
@mh105 can you provide your opinion about the following question:

* is setting the default value of 100ms backwards and forwards for blink padding acceptable based on your expertise (i.e., this occurs just prior to the interpolation step)

**Comment by mh105** [comment]
Here "blink padding" is referring to a "bleeding" when masking pupil data around detected blink periods, right? I think 100ms is a bit too much. 50ms on both ends should be more than enough. I've been doing 40ms before.

**Comment by shawntz** [comment]
yes -- thanks; this is helpful, thanks @mh105. i was particularly wondering because [this package -- the `pupillometry` R package](https://github.com/dr-JT/pupillometry) defaults to `75 ms`, and the paper for the `GazeR` package states the following:

> "A less trivial matter in pre-processing pupil data is deciding how many data points to remove before and after the blink. **It has generally been recommended that data 100 ms before and after the blink should be eliminated.** There are several ways one can deal with blinks (see Hershman, Henik, & Cohen, [2018](https://link.springer.com/article/10.3758/s13428-020-01374-8#ref-CR20)). One method is to eliminate all blinks from a trial. This is generally not recommended as it can eliminate too much data, resulting in a loss of power. **A more acceptable approach, and the one implemented in gazeR, is to extend the time window around the blinks so the interpolation starts 100-200 ms before the blink and continues after the blink (Nyström, Hooge, & Andersson, [2016](https://link.springer.com/article/10.3758/s13428-020-01374-8#ref-CR33)**; Satterthwaite et al., [2007](https://link.springer.com/article/10.3758/s13428-020-01374-8#ref-CR38)). Extending the time window around the blinks eliminates spurious samples caused by the closing and opening of the eyelids. The extend_blinks function implements this method, with the fillback argument specifying how far blinks should extend back in time (before the blink) and the fillforward argument specifying how far blinks should extend forward in time (after the blink). This function is robust to different sampling rates as long as the eye-tracker sampling rate is specified in the hz argument. **For this experiment, the tracker sampled at 250Hz (once every 4 ms) and blinks were extended 100 ms forward and backward in time.**"

Geller, J., Winn, M.B., Mahr, T. et al. GazeR: A Package for Processing Gaze Position and Pupil Size Data. Behav Res 52, 2232–2255 (2020). https://doi.org/10.3758/s13428-020-01374-8

**Comment by mh105** [comment]
I think there's an important trade-off to consider here. If one is just removing `x`ms before and after blinks to _eliminate_ data points, it's fine to remove a bit extra and just be on the conservative side. However, we often want to do interpolation to recover the blink periods so we don't have to deal with missing data during analysis. In this case, extending the time window far out has a greater risk of interpolating between two points that may be so far apart that drawing a line between them no longer makes sense - this is always a concern when interpolating, but adding 200ms to every blink period makes it more likely a problem.

My recommendation here is to eliminate as few additional data points as possible beyond what eye tracker detected blink epochs already remove. Bleed around blink periods **just long enough** to get rid of the majority of deflections due to eye-lid movements; tiny bits of remaining transients will get handled by your other `despeed` (now `detransient`) function. If after the default 50ms bleeding people still see a lot of fluctuations around blink periods (thanks to the visualization that will be available in `eyeris`, people can tell what `deblink` does), then they can gradually increase the bleeding duration until they feel satisfied.

Going the other way around, i.e., removing more than necessary just to be safe, is difficult to evaluate its consequences and to deduce whether it has masked important temporal dynamics in the pupillary response, especially when we don't know what the pupillary response should look like in the first place. Chopping away data against on a known artifact on pupillometry data is easier than hoping that interpolating too much doesn't introduce unknown artifacts, imo.

**Comment by shawntz** [comment]
These are really good points to consider here. I will try to make the evaluation of this parameter intuitive within the corresponding visualization steps. Really appreciate your insight on this @mh105! :muscle:

**Comment by mh105** [comment]
This functionality is hopefully easy enough to implement, so it would be great to have it for the CRAN release milestone. I can see that some users might prefer to have a slightly longer bleeding _after_ the blink compared to _before_ the blink. But I defer to @shawntschwartz's call on this!

**Comment by shawntz** [comment]
agreed with this @mh105 -- thanks for the nudge!
