### ISSUE TITLE
feature request: diagnostic plots of entire timeseries + epochs

### ISSUE THREAD

**Issue by shawntz** [shawntz/eyeris#7]
features/requirements:
- [x] change plotting mechanism to base graphics to remove `ggplot2` dependency + speed up plotting!
- [x] allow step-wise interactive plotting of particular windows
- [x] ~~paginate full time series plots to demonstrate effects of each step (overlay each step)~~
> for now, this functionality has been tabled to avoid needing to figure out flexible solutions for the limited interactive features provided by the `R` graphics window out of the box. perhaps this could later become part of an interactive `shiny` interface, but for now, it seems reasonable to take the approach of just plotting a subset of the timeseries for qualitative assessment (and then allowing the user themselves to take the raw/preprocessed timeseries and plot them however else they'd like on their own). -shawn (sept. 12, 2024)
 
- [x] ~~allow these step-wise plots to be generated and saved out (especially if user is running analysis on a headless machine)~~
> similar to above, this can be a feature we can easily implement as a flag within the function, but doesn't seem like it's necessarily our responsibility to provide the additional scaffolding to save out these plots given; instead, we can relegate this responsibility to the end user, who can use their graphics function of choice (i.e., `pdf()`, `png()`, etc.) to save out these diagnostic plots as they so please to do. -shawn (sept. 12, 2024)

**Comment by shawntz** [comment]
@mh105 can you provide any additional thoughts about the two points i raised in the initial issue comment above? thanks!

**Comment by mh105** [comment]
>paginate full time series plots to demonstrate effects of each step (overlay each step)

I agree. `Diagnostic plots` and `Plots of entire time series` are two different concepts that serve different purposes. For a preprocessing package `eyeris` (at least for now) shouldn't have to worry about providing a nice pagination GUI to flip through the entire time series / all epochs. We may add this bonus functionality later, but for now it's sufficient to provide enough visualization for diagnostic evaluation. 

My suggestion is to randomly pick 3 epochs (don't just show one because that doesn't feel representative enough) and show the step-by-step impacts of the processing pipeline. So you could have different steps across the rows, and 3 columns, or transpose it. This way the qualitative assessment is not just on a single epoch. And when people should be able to call the plot function again, which should randomly select yet another 3 epochs -> so if people want they can just do this however many times their hearts desire until they feel they have reached sufficient qualitative assessment. If the pipeline didn't epoch, just randomly pick 3 five-second periods and do the same thing. And you are right that users will have access to all the raw/preprocessed time series anyways, so they can plot them however they want. What do you think about this suggestion?

>allow these step-wise plots to be generated and saved out (especially if user is running analysis on a headless machine)

Oh yeah no. Saving svg is easy enough in R that you don't really want to spend the efforts to accept and parse a saving directory and all that. People can and should be able to chain a saving call to the figure handle themselves, if they are comfortable enough to run the pipeline on headless machines.

**Comment by shawntz** [comment]
great, thanks! glad we're on the same page about this @mh105!
